### ISSUE TITLE
refactor: rename arguments in `readSCP`

### ISSUE THREAD

**Issue by cvanderaa** [UCLouvain-CBIO/scp#17]
I think the `quantTable` should be renamed to `featureTable` as this table not only contains quantifications but also the metadata that will be stored in the `rowData`.

Similarly, `metaTable` is confusing as it could be feature metadata as well as sample metadata. We could simply rename `metaTable` to `colData` since in the end, the table will become the `colData`.

**Comment by lgatto** [comment]
- I agree that naming that data `feature` is better. I am however unsure about the `Table` part. It can be a spread sheet, a `data.frame`, ... may be simply `featureData`?
- A definitive yes for `colData`.

**Comment by cvanderaa** [comment]
Indeed, `featureData` sounds much better!

**Comment by cvanderaa** [comment]
Done by commit 0f08a4b328c478562d99066bb57929e703d3f71f
