### ISSUE TITLE
Deprecate `transferColDataToAssay`

### ISSUE THREAD

**Issue by cvanderaa** [UCLouvain-CBIO/scp#18]
`transferColDataToAssay` should be removed since I think this can be confusing for new users and it will also promote messing up the `colData`. I used this function to extract assays along with their associated `colData`, but the `getWithColData` function from the `MultiAssayExperiment` package does the job!

**Comment by lgatto** [comment]
Yes, good idea!

**Comment by cvanderaa** [comment]
Do you think I should go through the [deprecation process](https://www.bioconductor.org/developers/how-to/deprecation/) or can I just drop the function (and document it in `NEWS.md`)?

**Comment by lgatto** [comment]
The package is very recent, so it might not be too big of an offence to remove it silently.

**Comment by cvanderaa** [comment]
Done by commit https://github.com/UCLouvain-CBIO/scp/commit/2792311da2f852ad07922dfa3f33fecc6aefb862
