### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/scp#2]
Prepare a small vignette. Content to be discussed.

**Comment by cvanderaa** [comment]
I wrote a first draft of the vignette. However, I don't evaluate the code chunks because `computeMedianCV` throws an error. I believe we need to solve issue #7 first.

**Comment by cvanderaa** [comment]
I improved the vignette. Let me know if you think there are things to change. Otherwise, we can close this issue.
