### ISSUE TITLE
vignette header

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/scp#20]
The vignette header looks broken on the pkgdown page

![2021-02-05-190943_774x822_scrot](https://user-images.githubusercontent.com/384198/107071960-c7ab5c00-67e5-11eb-8081-abb630664f6a.png)

**Comment by cvanderaa** [comment]
Sorry, it took me some time to catch  a hiding whitespace, but it should be good by https://github.com/UCLouvain-CBIO/scp/commit/cea242487d9a587189c483aae09f3d3d2e8cb40c
