### ISSUE TITLE
Vignette/data import/readSCP

### ISSUE THREAD

**Issue by edemmott** [UCLouvain-CBIO/scp#21]
The maxquant evidence file used for the vignette appears to deviate from the default maxquant. To get it to behave I needed to rename a number of columns:

names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.1"] <- "RI1"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.2"] <- "RI2"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.3"] <- "RI3"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.4"] <- "RI4"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.5"] <- "RI5"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.6"] <- "RI6"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.7"] <- "RI7"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.8"] <- "RI8"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.9"] <- "RI9"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.10"] <- "RI10"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.11"] <- "RI11"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.12"] <- "RI12"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.13"] <- "RI13"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.14"] <- "RI14"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.15"] <- "RI15"
names(mqSCPdata)[names(mqSCPdata) == "Reporter.intensity.corrected.16"] <- "RI16"
names(mqSCPdata)[names(mqSCPdata) == "Raw.file"] <- "Set"

**Comment by cvanderaa** [comment]
Hello @edemmott ,
Thank you very much for your feedback. I'm not sure to understand whether you need to rename the column names to run the vignette/example (should not be the case) or to run on your own data (then indeed renaming might be required). Anyway, I think you raise a good point, that is the example data should contain the default MaxQuant column names. I'll adapt this soon. 
Best, 
Chris

**Comment by cvanderaa** [comment]
I adapted the example data, the documentation and vignette. I hope this improvement is in line with the issue raised.

**Comment by cvanderaa** [comment]
I will close this issue because we will create a new vignette to better describe how to import data using `scp` (see issue #23 ). Any suggestions there are welcome!
