### ISSUE TITLE
pep2qvalue missing?

### ISSUE THREAD

**Issue by edemmott** [UCLouvain-CBIO/scp#26]
pep2qvalue function appears missing. At least from the dev version.

BiocManager::install("UCLouvain-CBIO/scp") # Dev version

library("scp")
> session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.4 (2021-02-15)
 os       macOS Catalina 10.15.6      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/London               
 date     2021-07-18                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────
 ! package              * version  date       lib source                                         
   AnnotationFilter       1.14.0   2020-10-27 [1] Bioconductor                                   
   assertthat             0.2.1    2019-03-21 [1] CRAN (R 4.0.2)                                 
   Biobase              * 2.50.0   2020-10-27 [1] Bioconductor                                   
   BiocGenerics         * 0.36.1   2021-04-16 [1] Bioconductor                                   
 V BiocManager            1.30.10  2021-06-15 [1] CRAN (R 4.0.2)                                 
   bitops                 1.0-7    2021-04-24 [1] CRAN (R 4.0.2)                                 
   cachem                 1.0.5    2021-05-15 [1] CRAN (R 4.0.2)                                 
   callr                  3.7.0    2021-04-20 [1] CRAN (R 4.0.2)                                 
   cli                    3.0.0    2021-06-30 [1] CRAN (R 4.0.2)                                 
   colorspace             2.0-2    2021-06-24 [1] CRAN (R 4.0.2)                                 
   crayon                 1.4.1    2021-02-08 [1] CRAN (R 4.0.2)                                 
   curl                   4.3.2    2021-06-23 [1] CRAN (R 4.0.2)                                 
   DBI                    1.1.1    2021-01-15 [1] CRAN (R 4.0.2)                                 
   DelayedArray           0.16.3   2021-03-24 [1] Bioconductor                                   
   desc                   1.3.0    2021-03-05 [1] CRAN (R 4.0.2)                                 
   devtools             * 2.4.2    2021-06-07 [1] CRAN (R 4.0.2)                                 
   digest                 0.6.27   2020-10-24 [1] CRAN (R 4.0.2)                                 
 V dplyr                  1.0.5    2021-06-18 [1] CRAN (R 4.0.2)                                 
 V ellipsis               0.3.1    2021-04-29 [1] CRAN (R 4.0.2)                                 
   evaluate               0.14     2019-05-28 [1] CRAN (R 4.0.1)                                 
 V fansi                  0.4.2    2021-05-25 [1] CRAN (R 4.0.2)                                 
   fastmap                1.1.0    2021-01-25 [1] CRAN (R 4.0.2)                                 
   fs                     1.5.0    2020-07-31 [1] CRAN (R 4.0.2)                                 
   generics               0.1.0    2020-10-31 [1] CRAN (R 4.0.2)                                 
   GenomeInfoDb         * 1.26.7   2021-04-08 [1] Bioconductor                                   
   GenomeInfoDbData       1.2.4    2021-03-13 [1] Bioconductor                                   
   GenomicRanges        * 1.42.0   2020-10-27 [1] Bioconductor                                   
   ggplot2              * 3.3.5    2021-06-25 [1] CRAN (R 4.0.2)                                 
   glue                   1.4.2    2020-08-27 [1] CRAN (R 4.0.2)                                 
   gtable                 0.3.0    2019-03-25 [1] CRAN (R 4.0.2)                                 
   htmltools              0.5.1.1  2021-01-22 [1] CRAN (R 4.0.2)                                 
   IRanges              * 2.24.1   2020-12-12 [1] Bioconductor                                   
 V knitr                  1.31     2021-04-24 [1] CRAN (R 4.0.2)                                 
   lattice                0.20-44  2021-05-02 [1] CRAN (R 4.0.2)                                 
   lazyeval               0.2.2    2019-03-15 [1] CRAN (R 4.0.2)                                 
   lifecycle              1.0.0    2021-02-15 [1] CRAN (R 4.0.2)                                 
   magrittr             * 2.0.1    2020-11-17 [1] CRAN (R 4.0.2)                                 
   MASS                   7.3-54   2021-05-03 [1] CRAN (R 4.0.2)                                 
   Matrix                 1.3-4    2021-06-01 [1] CRAN (R 4.0.2)                                 
   MatrixGenerics       * 1.2.1    2021-01-30 [1] Bioconductor                                   
   matrixStats          * 0.59.0   2021-06-01 [1] CRAN (R 4.0.2)                                 
   memoise                2.0.0    2021-01-26 [1] CRAN (R 4.0.2)                                 
   MsCoreUtils            1.2.0    2020-10-27 [1] Bioconductor                                   
   MultiAssayExperiment * 1.16.0   2020-10-27 [1] Bioconductor                                   
   munsell                0.5.0    2018-06-12 [1] CRAN (R 4.0.2)                                 
 V pillar                 1.5.1    2021-05-16 [1] CRAN (R 4.0.2)                                 
   pkgbuild               1.2.0    2020-12-15 [1] CRAN (R 4.0.2)                                 
   pkgconfig              2.0.3    2019-09-22 [1] CRAN (R 4.0.2)                                 
   pkgload                1.2.1    2021-04-06 [1] CRAN (R 4.0.2)                                 
   prettyunits            1.1.1    2020-01-24 [1] CRAN (R 4.0.2)                                 
   processx               3.5.2    2021-04-30 [1] CRAN (R 4.0.2)                                 
   ProtGenerics           1.22.0   2020-10-27 [1] Bioconductor                                   
   ps                     1.6.0    2021-02-28 [1] CRAN (R 4.0.2)                                 
   purrr                  0.3.4    2020-04-17 [1] CRAN (R 4.0.2)                                 
 V QFeatures            * 1.0.0    2021-07-17 [1] Github (rformassspectrometry/QFeatures@be2640e)
   R6                     2.5.0    2020-10-28 [1] CRAN (R 4.0.2)                                 
   RCurl                  1.98-1.3 2021-03-16 [1] CRAN (R 4.0.2)                                 
   remotes                2.4.0    2021-06-02 [1] CRAN (R 4.0.2)                                 
 V rlang                  0.4.10   2021-04-30 [1] CRAN (R 4.0.2)                                 
 V rmarkdown              2.7      2021-06-15 [1] CRAN (R 4.0.2)                                 
   rprojroot              2.0.2    2020-11-15 [1] CRAN (R 4.0.2)                                 
   rstudioapi             0.13     2020-11-12 [1] CRAN (R 4.0.2)                                 
   S4Vectors            * 0.28.1   2020-12-09 [1] Bioconductor                                   
   scales                 1.1.1    2020-05-11 [1] CRAN (R 4.0.2)                                 
 V scp                  * 1.0.0    2021-07-17 [1] Github (UCLouvain-CBIO/scp@3127425)            
   sessioninfo            1.1.1    2018-11-05 [1] CRAN (R 4.0.2)                                 
   SingleCellExperiment   1.12.0   2020-10-27 [1] Bioconductor                                   
   SummarizedExperiment * 1.20.0   2020-10-27 [1] Bioconductor                                   
   testthat               3.0.4    2021-07-01 [1] CRAN (R 4.0.2)                                 
 V tibble                 3.1.0    2021-05-16 [1] CRAN (R 4.0.2)                                 
 V tidyselect             1.1.0    2021-04-30 [1] CRAN (R 4.0.2)                                 
 V tinytex                0.30     2021-05-29 [1] CRAN (R 4.0.2)                                 
   usethis              * 2.0.1    2021-02-10 [1] CRAN (R 4.0.2)                                 
 V utf8                   1.1.4    2021-03-12 [1] CRAN (R 4.0.2)                                 
 V vctrs                  0.3.6    2021-04-29 [1] CRAN (R 4.0.2)                                 
   withr                  2.4.2    2021-04-18 [1] CRAN (R 4.0.2)                                 
 V xfun                   0.22     2021-06-15 [1] CRAN (R 4.0.2)                                 
   XVector                0.30.0   2020-10-28 [1] Bioconductor                                   
   yaml                   2.2.1    2020-02-01 [1] CRAN (R 4.0.2)                                 
   zlibbioc               1.36.0   2020-10-28 [1] Bioconductor                                   

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

 V ── Loaded and on-disk version mismatch.

**Comment by edemmott** [comment]
Is this now computeFDR?

**Comment by edemmott** [comment]
Now works for me. Minor thing:
groupBy term needed changing from the vignette. Maxquant standard output could be done using 'Leading.razor.protein' as below or 'Proteins'/'Leading.proteins'. In the vignette this is simply 'protein' which doesn't work with unmodified maxquant files. Code below seems to work fine.

# Calculate Protein-level Q-value
scp <- pep2qvalue(scp,
                  i = 1:96,
                  PEP = "dart_PEP",
                  groupBy = "Leading.razor.protein",
                  rowDataName = "qvalue_proteins")

**Comment by cvanderaa** [comment]
Excellent advice, thanks for pointing this out! I saw there were other places where I used `protein` that I now replaced by `Leading.razor.protein` for consistency. The vignette is updated and so will the online documentation soon.
