### ISSUE TITLE
Minor: aggregatefeaturesoverassays

### ISSUE THREAD

**Issue by edemmott** [UCLouvain-CBIO/scp#27]
The fcol name given in the vignette is non-standard for maxquant and doesn't work without renaming. A suitable alternative is 'Sequence' or 'Modified.sequence' as below.

scp <- aggregateFeaturesOverAssays(scp,
                                   i = 1:100,
                                   fcol = "Modified.sequence", # Note change from 'peptide'
                                   name = paste0("peptides_", names(scp)),
                                   fun = matrixStats::colMedians, na.rm = TRUE)

**Comment by cvanderaa** [comment]
Again, thanks for the remark! This has been adapted!
