### ISSUE TITLE
apply medians over cols or colMedians

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/scp#31]
In this [code chunk](https://github.com/UCLouvain-CBIO/scp/blob/master/vignettes/scp.Rmd#L574-L578) in the `scp` vignette, you apply the median over the 2nd margin. Is this meant to be an illustration of `apply`? Otherwise, `matrixStats::colMedians()` would possibly be a better fit.

**Comment by cvanderaa** [comment]
closed by https://github.com/UCLouvain-CBIO/scp/commit/2b50ab872d07e13d9fb99d47ecf3d484e827ca7a
