### ISSUE TITLE
Improve the readSCP vignette 

### ISSUE THREAD

**Issue by cvanderaa** [UCLouvain-CBIO/scp#32]
Following the SCP2021 presentation, rename some of the vocabulary used (eg feature data -> input table) and redraw some of the figures.

**Comment by cvanderaa** [comment]
Done since https://github.com/UCLouvain-CBIO/scp/commit/8b1c4e34ea637f6c897501a7183226437e1fbfa1,
there is a strange build issue however since then. I'll try to fix that before closing the issue.

**Comment by cvanderaa** [comment]
Current message is 
```
Warning in read.dcf(desc, fields = "Package") :
  cannot open compressed file '/__w/scp/scp/check/scp_1.5.1.tar.gz/DESCRIPTION', probable reason 'Not a directory'
Error in read.dcf(desc, fields = "Package") : cannot open the connection
Calls: <Anonymous> -> .get_package_name -> read.dcf
Execution halted
Error: Process completed with exit code 1.
```
That does not look like an `scp' related error...

**Comment by lgatto** [comment]
I see the same on other repos. I suspect some external reason.

**Comment by lgatto** [comment]
Fixed now. Closing this issue.
