### ISSUE TITLE
Error in computeFDR

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/scp#4]
Running `example(computeFDR)`:

```r
> example(computeFDR)

cmpFDR> scp1 <- computeFDR(scp1,
cmpFDR+                    i = 1,
cmpFDR+                    groupCol = "Sequence",
cmpFDR+                    pepCol = "PEP")
Error in computeFDR(scp1, i = 1, groupCol = "Sequence", pepCol = "PEP") : 
  'PEP' must link to a probability in (0, 1)
```

**Comment by cvanderaa** [comment]
Oh yes, I wanted to discuss this with you. 

I have put a check that makes sure the users supply a probability, but it seems that MaxQuant's PEP computation can go beyond 1. See for example:
```r
range(rowData(scp1[[1]])$PEP)
```
```
[1] 1.6819e-21 2.8325e+00
```
An easy fix is to use the DART-ID corrected PEPs, `dart_PEP`. 

Should I remove the check or change `PEP` to `dart_PEP`?

**Comment by cvanderaa** [comment]
Also you will run in the following warning:
```
 Features are sorted. This is only needed when replicating the SCoPE2 analysis
See also https://github.com/SlavovLab/SCoPE2/issues/3
```
This is because part of the implementation is adapted to exactly replicate the FDR computation from the SCoPE2 analysis (see [this issue](https://github.com/SlavovLab/SCoPE2/issues/3))

**Comment by lgatto** [comment]
- Yes, please use `dart_PEP` and document this and the check in the man page. 
- Maybe change the warning to a message.
