### ISSUE TITLE
SCP.replication

### ISSUE THREAD

**Issue by xinpengdun** [UCLouvain-CBIO/scp#43]
I would like to install SCP.replication, however, I have the following issue for the installation, pleases could you help me solve the issue? 
Thanks!

BiocManager::install("UCLouvain/SCP.replication")

>BiocManager::install("UCLouvain/SCP.replication") 

'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for details. Replacement repositories:     CRAN: https://cran.rstudio.com/ Bioconductor version 3.17 (BiocManager 1.30.21.1), R 4.3.0 (2023-04-21 ucrt) Installing github package(s) 'UCLouvain/SCP.replication' Error: Failed to install 'unknown package' from GitHub:   HTTP error 404.   Not Found    Did you spell the repo owner (`UCLouvain`) and repo name (`SCP.replication`) correctly?   - If spelling is correct, check that you have the required permissions to access the repo.

>

**Comment by lgatto** [comment]
There was a typo in the command, which is fixed now.
