### ISSUE TITLE
Help to replicate graph

### ISSUE THREAD

**Issue by prvst** [UCLouvain-CBIO/scp#47]
Hello, could you please show me how to replicate Figures 8, and 9 from this https://arxiv.org/abs/2310.13598?

Thanks

**Comment by lgatto** [comment]
Not sure it's available in the Rmd file on the zenodo archive (10.5281/zenodo.8417228), but it's a rather standard type of plot that can be generated with data in a `QFeatures` object. There's a similar figure in section 5.4.9 (figure 5/14) in the [Quantitative data](https://rformassspectrometry.github.io/book/sec-quant.html) chapter of the R4MS book. 

Would this address your question?

**Comment by prvst** [comment]
Yes, that helps. I was trying to figure it out how to pull data from the different layers (PSM, peptides, and protein) into one data frame. 

Thanks, Laurent

Also, nice job with the publication above, good to see people working with open and clear methods that make sense, for single-cell.

Cheers,
