### ISSUE TITLE
DIA / LFQ compatibility

### ISSUE THREAD

**Issue by prvst** [UCLouvain-CBIO/scp#48]
Hello, Is scp compatible with DIA or LFQ data? If that's the case, can you please provide me with an example of how to structure the quantitative input table and the sample input table, for the readSCP method? 

Thank you

**Comment by lgatto** [comment]
Yes, and type of DIA/DDA or labelled/LFQ data can be analysed with QFeatures/scp. We have a collection of replication analyses in [SCP.replication](https://uclouvain-cbio.github.io/SCP.replication), that include LFQ experiments. 

You have two options
- you either load a table with all precursor-level cells/acquisitions along the rows into you starting assay, or
- have a series 1-column assays for each cell/acquisition - in that case, the sample data in the `readSCP()` function corresponds to one cell/acquisition. 

@cvanderaa can probably provide more details.

**Comment by prvst** [comment]
Thanks, Laurent.

I reviewed some examples, such as the Brunner data, which uses DIA data, but the example starts with QFeature objects already built. I'm still learning how to work with the scp and QFeatures package, I'm struggling a bit to figure it out how to get my input data organized when there are no channels.

**Comment by lgatto** [comment]
You can find the scripts that generated these QFeatures objects in the [scpdata repo](https://github.com/UCLouvain-CBIO/scpdata/tree/master/inst/scripts). If these don't help, let us know, and we'll provide further details.

@cvanderaa - we should probably update the `readSCP()` documentation or vignette with more details/examples.

**Comment by prvst** [comment]
Perfect, thank you!

**Comment by lgatto** [comment]
Here's some update with regard to reading DIA-NN output to create QFeatures:

- [readQFeatures()](https://rformassspectrometry.github.io/QFeatures/reference/readQFeatures.html) has been updated and streamlined
- [readQFeaturesFromDIANN()](https://rformassspectrometry.github.io/QFeatures/reference/readQFeaturesFromDIANN.html) can be used to import label-free and plexDIA/mTRAQ data produced by DIA-NN

I'm going to close the issue, but feel free to re-open (or open a new one) if you have questions or comments.
