### ISSUE TITLE
scplainer: could not find function "scpModelWorkflow"

### ISSUE THREAD

**Issue by shimin-chen** [UCLouvain-CBIO/scp#53]
Hello,

Thank you for developing the tool and all the tutorial materials! I find the tutorial very helpful and easy to follow.

I am hoping to try out the scplainer workflow (basically trying to replicate this: [https://uclouvain-cbio.github.io/SCP.replication/articles/scplainer_leduc2022.html](https://uclouvain-cbio.github.io/SCP.replication/articles/scplainer_leduc2022.html). When I get to the data modeling part using scpModelWorkflow(), I got an error: could not find function "scpModelWorkflow". I am at version 1.13.1. 

Thank you.
Shimin

**Comment by lgatto** [comment]
You will need to install it with

```r
BiocManager::install("UCLouvain-CBIO/scp", ref = "scplainer")
```

**Comment by shimin-chen** [comment]
It is working now. Thank you!
