### ISSUE TITLE
error when using filterFeatures

### ISSUE THREAD

**Issue by Axe2Ash** [UCLouvain-CBIO/scp#61]
Hi, I am new to scp and got an error when using it. I follow these tutorials:
1)https://bioconductor.org/packages/release/bioc/vignettes/scp/inst/doc/advanced.html#4_Modify_the_feature_annotations
2)https://uclouvain-cbio.github.io/SCP.replication/articles/brunner2022.html

I want to only use a subset of proteins from my dataset for statistics and added a column named "cycle" from a list of proteins of interest (follow tutorial 1). Proteins of interest have values 1.1, others are zeroes.
the "cycle" column is in the same location as the column "mean" and "detected" from the filter protein section in tutorial 2.
But when I tried to filter out proteins, I got "Error in rowSums(out) : 'x' must be numeric"

Coul you help me to fix this?
Thanks
Arthur
![Capture](https://github.com/UCLouvain-CBIO/scp/assets/148263679/62c2573e-eeb5-4835-8b70-bd186ad646c0)

**Comment by lgatto** [comment]
Difficult to say where the error comes from. 

What class is `Evosample` of? Could you confirm it is a `QFeatures`. How many assays is it composed of? And do all, some or only 1 have the cycle variable?

I will have a look if you are able to share the object.

**Comment by lgatto** [comment]
To give you some hints as to where this error could come from, it is typically thrown when the variable you want to filter on, here `cycle`, isn't found in any assay/set in the `QFeatures`object, here `Evosample` (but waiting for confirmation).

**Comment by lgatto** [comment]
I think I know what is happing - could you delete the `cycle` variable in your working environment.
