### ISSUE TITLE
scp_data_modelling vignette

### ISSUE THREAD

**Issue by edemmott** [UCLouvain-CBIO/scp#74]
Details on the upfront data processing are not sufficiently detailed to permit replication.

For example - was the data normalised to a reference? It looks like the reference was not used and no normalisation performed? Is this correct.

It also states median intensity was calculated. Was this median reporter intensity? Or peptide intensity and how/when was this done? What commands?

**Comment by edemmott** [comment]
Ok. I think I found this info through SCP replication. Good to include a link to it

**Comment by lgatto** [comment]
Hi @edemmott - sorry for the delay, I had a big grant last week and have been travelling since. 

Thank you for the suggestion to add a link. The SCP.replication repo was created first, and we forgot to link to it when writing the _scplainer_ vignette.

**Comment by edemmott** [comment]
Fingers crossed for the grant!


On 3 Oct 2024, at 19:53, Laurent Gatto ***@***.***> wrote:

﻿

Caution: This email originated from outside of the University. Do not click links or open attachments unless you recognise the source of this email and know the content is safe. Check sender address, hover over URLs and don't open suspicious email attachments.

Hi @edemmott<https://github.com/edemmott> - sorry for the delay, I had a big grant last week and have been travelling since.

Thank you for the suggestion to add a link. The SCP.replication repo was created first, and we forgot to link to it when writing the scplainer vignette.

**Comment by lgatto** [comment]
Thanks! 

The link was [added](https://github.com/UCLouvain-CBIO/scp/commit/aa4b66cf825a2d7990004ec96334edf77864add8).
