### ISSUE TITLE
vignette: Filter assays based on detected features

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/scp#9]
In your example, the filtering doesn't remove any features. Indeed, you mention 

> Note in our example all assays have sufficient number of PSMs, hence no assay is removed.

I was wondering if you couldn't use either different a value that removes an assay (but only for demonstration and then carry on with all of them), or add a 4th handcrafted low-quality assay with less PSMs that would be filtered out.

**Comment by cvanderaa** [comment]
Indeed, I was hesitating to do this when writing that note. I would go for the 2nd solution and create a mock assay. What do you think about calling it `failed_run` to explicit the procedure?

**Comment by cvanderaa** [comment]
In the end, I added one of the blank samples available from the SCoPE2 dataset. 

```r
readSCP(mqScpData, 
        sampleAnnotation, 
        batchCol = "Set", 
        channelCol = "Channel")
```
```
An instance of class QFeatures containing 4 assays:
 [1] 190222S_LCA9_X_FP94BM: SingleCellExperiment with 334 rows and 16 columns 
 [2] 190321S_LCA10_X_FP97_blank_01: SingleCellExperiment with 109 rows and 16 columns 
 [3] 190321S_LCA10_X_FP97AG: SingleCellExperiment with 433 rows and 16 columns 
 [4] 190914S_LCB3_X_16plex_Set_21: SingleCellExperiment with 321 rows and 16 columns 
```

So, this new `190321S_LCA10_X_FP97_blank_01` assay is real data
